### ISSUE TITLE
Named terminal support in the REST API

### ISSUE THREAD

**Issue by wudstrand** [jupyter-server/jupyter_server_terminals#66]
### Problem

When creating terminals via the REST api (i.e. a `POST` request to `/api/terminals`) the terminal name/id is an incrementing integer. For my use case I would like to control the names/ids of the terminals for organizational purposes. 

### Proposed Solution

I believe the solution is would be an easy update to the `/api/terminals` `POST` request by adding the ability to override the terminal name/id in the body of the request. Alternatively you could provide a  `/api/terminals/{terminal id}` `POST` endpoint for creating named terminals.

**Comment by Zsailer** [comment]
Hi @wudstrand, I transferred your issue here, since terminals are now an extension of Jupyter Server.

I believe what you want is already possible with terminals today (though, not well documented in our REST API spec). You can pass a body to the `POST` endpoint with a name given, e.g.

```
POST /api/terminals

BODY: 
{
  "name": "my-terminal"
}
```

Does this cover your usecase?
